### ISSUE TITLE
Certain DOM elements start with no color until setColorMode() is called

### ISSUE THREAD

**Issue by AndrewNow** [baristikir/next-theme-mode#1]
Hi, 

I'm encountering a strange issue. On page load, certain elements follow the theme, and others don't (notice the nav for example):

![image](https://user-images.githubusercontent.com/57265008/187722358-ac3d1256-3c0f-47ef-9455-05beb2b6c50f.png)

Strangely, no matter what mode is cached on page reload, the colors that *do* load are the light mode colors.

Until I call my `handleToggle` function, then the rest of the elements gain their intended color: 

![image](https://user-images.githubusercontent.com/57265008/187722497-2903e36d-1c0b-4914-ae14-0db898a92d04.png)

When I toggle the button a third time, I get the dark mode you would expect:

![image](https://user-images.githubusercontent.com/57265008/187722884-e0086676-692d-4d0b-9a67-24947fa8eb40.png)

What is causing this behaviour? Also, does this package account for `prefers-color-scheme`?

My code is as follows:

```js
// _document.js
import React from "react";
import { Head, Html, Main, NextScript } from "next/document";
import { ScriptHydrationTheme } from "next-theme-mode";
import { Theme } from "../styles/Theme";

export default function Document() {
  return (
    <Html lang="fr">
      <Head />
      <body>
        <ScriptHydrationTheme themes={Theme} />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
```

```js
// toggleDarkMode.js
...
import { useTheme } from "next-theme-mode";

const ToggleDarkMode = () => {
  const { colorMode, setColorMode } = useTheme();

  const isDark = colorMode === "dark" ? true : false;

  const handleToggle = () => {
    isDark ? setColorMode("light") : setColorMode("dark");
  };

  return (
        <Button onClick={handleToggle} aria-label="toggle dark mode">
          <Circle />
          <small>Mode {isDark ? "sombre" : "claire"}</small>
        </Button>
  );
};
}
```

and finally, my `app.js`:

```js
const MyApp = ({ Component, pageProps, router }) => {
  return (
    <ThemeModeProvider customThemes={Theme}>
    <LazyMotion features={domAnimation}>
      <AnimatePresence exitBeforeEnter>
        <m.div
          // key="routerKey"
          key={router.asPath}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.7 }}
        >
          <Layout>
            <Cart>
              <Navbar mediaKitData={pageProps.footerLogos} />
              <Component {...pageProps} />
              <Footer logos={pageProps.footerLogos} />
            </Cart>
          </Layout>
        </m.div>
      </AnimatePresence>
    </LazyMotion>
    </ThemeModeProvider>
  );
};
```

**Comment by baristikir** [comment]
This is caused by the minified injected script and couldn't find a workaround at that time.

I recommend using https://github.com/pacocoursey/next-themes instead, due to lack of maintenance and development on this project.
